# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

title: Front in Vale
year: 2016
email: contato@frontinvale.com.br
description: Segundo evento de front-end no Vale do Para√≠ba.
keywords: 'frontend, front-end, html, html5, css, css3, javascript, js'
baseurl: ""
image_social: '/images/frontinvale-social.png'
url: "http://frontinvale.com.br"
twitter_username: frontinvale
github_username:  frontinvale
eventick: http://www.eventick.com.br/frontinvale2016

markdown: kramdown
